[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-rs", "run", 
  "--chip", "STM32F413ZHJx", 
  "--connect-under-reset", 
  "--log-format", "[{t} {L:>1} {f}:{l:>0}] {s}"
]

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "linker=flip-link",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]

[term]
# Control whether colored output is shown
color = "always"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[alias]
b =   "build"
br =  "build --release"
c =   "clean"
r =   "run --package arm"
rr =  "run --release --package arm"
t =   "test --package arm --no-fail-fast --tests -- --show-output --nocapture"
